openapi: 3.0.1
info:
  title: Home Assistant Plugin
  description: A Plugin for managing light and switches in your home. You can turn on and off lights and switches, and change the color of lights.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /lights/status:
    get:
      operationId: getLightsStatus
      summary: Get the list of the lights, their id and their status
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLightsStatusResponse'
  /set/{id}/{status}:
    post:
      operationId: set
      summary: Set the status of a light, turn or on or off
      parameters:
      - in: path
        name: id
        schema:
            type: string
        required: true
        description: The id of the light
      - in: path
        name: status
        schema:
            type: string
        required: true
        description: The status of the light
      responses:
        "200":
          description: OK
components:
  schemas:
    getLightsStatusResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of lights.